### ISSUE TITLE
Unable to build 'domain' on alpine

### ISSUE THREAD

**Issue by sudharshankakumanu** [OpenMined/PySyft#5834]
## Question
**Unable to build 'pygrid-domain' on an alpine base image with Python 3.8.**

## Further Information
I want to run a pygrid domain on our corp infrastructure, which uses the alpine base image. I am running into issues when `docker-compose up --build` with the following docker file, even after adding missing packages (apk add).

`Dockerfile`
```
FROM docker-*****/python_v3:9.1-alpine

RUN mkdir /app
WORKDIR /app
COPY pip.conf ${PYTHON_VIRTUAL_ENV_FOLDER}

RUN apk update

RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo git g++

RUN . ${PYTHON_VIRTUAL_ENV_FOLDER}/bin/activate && pip install poetry
COPY /app/domain/poetry.lock /app/domain/pyproject.toml /app/domain/entrypoint.sh /app/
COPY /app/domain/src /app/src

RUN . ${PYTHON_VIRTUAL_ENV_FOLDER}/bin/activate && rm -rf `poetry env list --full-path`
RUN . ${PYTHON_VIRTUAL_ENV_FOLDER}/bin/activate && \
    poetry export -f requirements.txt --output requirements.txt --without-hashes

RUN . ${PYTHON_VIRTUAL_ENV_FOLDER}/bin/activate && \
    pip install --upgrade pip && \
    poetry run pip install -U pip && \
    pip install -r requirements.txt

COPY --chown=asruser /container/root /
```

`docker-compose.yml`
```
version: '3.9'
services:
  domain:
    domainname: grid
    container_name: domain
    image: openmined/grid-domain:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=latest
        - APP=domain
        - APP_ENV=dev
    environment:
      - DATABASE_URL=postgresql://postgres:dbpass@domain-db:5432/domain
      - APP_ENV=dev
    ports:
      - "5002:5000"
    depends_on:
      - "domain-db"
    networks: ["net"]
  domain-db:
    domainname: grid
    container_name: db.domain
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: domain
    ports:
      - "5434:5432"
    networks: ["net"]
  
networks:
  net:
    name: local-grid  
```

`Error`
```
 => ERROR [14/15] RUN . /usr/src/venv/bin/activate &&     pip install --upgrade pip &&     poetry run pip install -U pip &&     pip install -r requirements.txt                                            467.9s 
------
 > [14/15] RUN . /usr/src/venv/bin/activate &&     pip install --upgrade pip &&     poetry run pip install -U pip &&     pip install -r requirements.txt:
#19 0.548 Looking in indexes: https://pypi.org/simple, https://pypi.python.org/simple
#19 0.549 Requirement already satisfied: pip in /usr/src/venv/lib/python3.8/site-packages (21.1.1)
#19 0.986 Collecting pip
#19 1.137   Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
#19 1.545 Installing collected packages: pip
#19 1.545   Attempting uninstall: pip
#19 1.546     Found existing installation: pip 21.1.1
#19 1.716     Uninstalling pip-21.1.1:
#19 1.818       Successfully uninstalled pip-21.1.1
#19 2.680 Successfully installed pip-21.1.3
#19 3.514 Looking in indexes: https://pypi.org/simple, https://pypi.python.org/simple
#19 3.515 Requirement already satisfied: pip in /usr/src/venv/lib/python3.8/site-packages (21.1.3)
#19 4.612 Looking in indexes: https://pypi.org/simple, https://pypi.python.org/simple
#19 4.614 Ignoring cffi: markers 'platform_python_implementation == "CPython" and sys_platform == "win32" and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0") and python_version >= "3.7" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6")' don't match your environment
#19 4.615 Ignoring colorama: markers 'python_version >= "3.6" and python_full_version < "3.0.0" and sys_platform == "win32" or sys_platform == "win32" and python_version >= "3.6" and python_full_version >= "3.5.0"' don't match your environment
#19 4.620 Ignoring pycparser: markers 'python_version >= "3.7" and python_full_version < "3.0.0" and platform_python_implementation == "CPython" and sys_platform == "win32" and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0") or platform_python_implementation == "CPython" and sys_platform == "win32" and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0") and python_full_version >= "3.4.0" and python_version >= "3.7"' don't match your environment
#19 4.624 Collecting syft@ git+https://github.com/OpenMined/PySyft@pygrid_demo
#19 4.625   Cloning https://github.com/OpenMined/PySyft (to revision pygrid_demo) to /tmp/pip-install-cvozyygg/syft_281731fbfcc2489a99b4e350dd009e1b
#19 4.625   Running command git clone -q https://github.com/OpenMined/PySyft /tmp/pip-install-cvozyygg/syft_281731fbfcc2489a99b4e350dd009e1b
#19 31.95   Running command git checkout -b pygrid_demo --track origin/pygrid_demo
#19 32.11   Branch 'pygrid_demo' set up to track remote branch 'pygrid_demo' from 'origin'.
#19 32.11   Switched to a new branch 'pygrid_demo'
#19 34.17 Collecting sympc@ git+https://github.com/OpenMined/SyMPC@main
#19 34.17   Cloning https://github.com/OpenMined/SyMPC (to revision main) to /tmp/pip-install-cvozyygg/sympc_bbc3745f1a7c47e180245d567df4e815
#19 34.17   Running command git clone -q https://github.com/OpenMined/SyMPC /tmp/pip-install-cvozyygg/sympc_bbc3745f1a7c47e180245d567df4e815
#19 36.57 Ignoring win32-setctime: markers 'sys_platform == "win32" and python_version >= "3.6"' don't match your environment
#19 36.88 Collecting aioice==0.7.5
#19 36.99   Downloading aioice-0.7.5-py3-none-any.whl (23 kB)
#19 37.31 Collecting aiortc==1.2.0
#19 37.34   Downloading aiortc-1.2.0.tar.gz (1.2 MB)
#19 38.47 Collecting alembic==1.5.8
.
.
#19 460.0 Collecting pynacl==1.4.0
#19 460.0   Downloading PyNaCl-1.4.0.tar.gz (3.4 MB)
#19 461.0   Installing build dependencies: started
#19 465.6   Installing build dependencies: finished with status 'done'
#19 465.6   Getting requirements to build wheel: started
#19 465.8   Getting requirements to build wheel: finished with status 'done'
#19 465.8     Preparing wheel metadata: started
#19 466.4     Preparing wheel metadata: finished with status 'done'
#19 466.4 Requirement already satisfied: pyparsing==2.4.7 in /usr/src/venv/lib/python3.8/site-packages (from -r requirements.txt (line 51)) (2.4.7)
#19 466.7 Collecting python-dateutil==2.8.1
#19 466.7   Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
#19 467.1 ERROR: Could not find a version that satisfies the requirement python-dp==1.0.2 (from versions: 0.1.0)
#19 467.1 ERROR: No matching distribution found for python-dp==1.0.2
```

Things I tried
* Verified not duplicate.
* Updated package versions to the latest on poetry.lock.
* Removed packages, but the same issue occurs for multiple other packages
* 
## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: alpine linux
 - Language Version:Python 3.8
 - Package Manager Version: Poetry (latest version)
