### ISSUE TITLE
Resolve MyPy Type Errors

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#8014]
## Description
Currently we only have mypy checks enabled for the serde path because it was temporarily broken and now there are small errors in most files so we can't turn them on in one go.

We need to progressively solve this by enabling some paths one PR at a time and fixing the issues.

```
- repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        name: mypy-syft
        always_run: true
        # files: "^packages/syft/src/syft/serde|^packages/syft/src/syft/util"
        files: "^packages/syft/src/syft/serde"
```
